main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('',views.home_view,name="home"),
    path('login/',views.LoginView.as_view(),name="login"),
    path('logout/',views.logout_view,name="logout"),    

    path('survey/',views.SurveyList.as_view(),name="survey_list"),
    path('survey/create/',views.SurveyCreate.as_view(),name="survey_create"),
    path('survey/<int:pk>/',views.SurveyDetail.as_view(),name="survey_detail"),
    path('survey/<int:pk>/delete/',views.SurveyDelete.as_view(),name="survey_delete"),
    path('survey/<int:pk>/update/',views.SurveyUpdate.as_view(),name="survey_update"),
    path('survey/<int:pk>/question_create/',views.QuestionCreate.as_view(),name="question_create"),
    path('survey/<int:pk>/<int:pk_q>/',views.QuestionDetail.as_view(),name="question_detail"),
    path('survey/<int:pk>/<int:pk_q>/delete/',views.QuestionDelete.as_view(),name="question_delete"),
    path('survey/<int:pk>/<int:pk_q>/answer_create/',views.AnswerCreate.as_view(),name="answer_create"),
    path('survey/<int:pk>/<int:pk_q>/<int:pk_answer>/',views.AnswerUpdate.as_view(),name="answer_update"),
    path('survey/<int:pk>/<int:pk_q>/<int:pk_answer>/delete',views.AnswerDelete.as_view(),name="answer_delete"),

    path('publication/',views.PublicationList.as_view(),name="publication_list"),
    path('publication/create/',views.PublicationCreate.as_view(),name="publication_create"),
    path('publication/<int:pk>/',views.PublicationDetail.as_view(),name="publication_detail"),
    path('publication/<int:pk>/update/',views.PublicationUpdate.as_view(),name="publication_update"),
    path('publication/<int:pk>/delete/',views.PublicationDelete.as_view(),name="publication_delete"),

]

medyatakip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        email = self.normalize_email(email)
        user = self.model(email=email, **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, **kwargs):
        user = self.create_user(**kwargs)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user    

class User(AbstractBaseUser,PermissionsMixin):    
    email = models.EmailField(verbose_name=('email address'), max_length=255,unique=True)
    is_staff = models.BooleanField(('staff status'), default=False,
        help_text=('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(('active'), default=True,
        help_text=('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(('date joined'), auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    def __unicode__(self):
        return self.email
    class Meta:
        swappable = 'AUTH_USER_MODEL'
        verbose_name = ('user')
        verbose_name_plural = ('users')        
        ordering = ['email']

class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,unique=True)
    fee = models.IntegerField(blank=False,null=False)

    intervals = (
        ('D' , 'Daily'),
        ('W' , 'Weekly'),
        ('M' , 'Monthly'),
        ('Y' , 'Yearly'),
    )
    report_interval = models.CharField(max_length=1,choices=intervals,default='M')
    date_last_report = models.DateTimeField(blank=True,null=True)
    class Meta:
        abstract = True
class Company(Customer):
    company_name = models.CharField(max_length=64)
    tax_no = models.IntegerField(unique=True)
    def __str__(self):
        return self.company_name
   
class Person(Customer):
    first_name = models.CharField(max_length=64)
    last_name  = models.CharField(max_length=64) 
    tc_id = models.IntegerField(unique=True)
    def get_name(self):
        return self.first_name +' '+ self.last_name
    def __str__(self):
        return self.get_name()
    
class Surveyor(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=64)
    last_name  = models.CharField(max_length=64)
    def get_name(self):
        return self.first_name +' '+ self.last_name
    def __str__(self):
        return self.get_name()

class Outlet(models.Model): 
    name = models.CharField(max_length=64)   
    def __str__(self):
        return self.name 
    
class Publication(models.Model):
    header = models.CharField(max_length=128)
    source = models.ForeignKey(Outlet,on_delete=models.PROTECT)  
    date_published= models.DateTimeField()
    date_created = models.DateTimeField(auto_now=True)
    text = models.TextField(verbose_name=('İçerik')) 
    releated_to = models.ManyToManyField(User,related_name='publications')
    #tags = models.ManyToManyField(Tags)
    def __str__(self):
        return self.header

class Survey(models.Model):
    name = models.CharField(max_length=128)
    ask_count = models.IntegerField(default=0)
    surveyors = models.ManyToManyField(Surveyor,related_name='surveys',blank=True)
    fee = models.IntegerField(default=5000)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Question(models.Model):
    name = models.CharField(max_length=255)
    survey = models.ForeignKey(Survey,on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Answer(models.Model):
    text = models.CharField(max_length=128)
    question = models.ForeignKey(Question,related_name="answer_set",on_delete=models.CASCADE)
    def __str__(self):
        return self.text

main/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django import forms
from .models import User as CustomUser

class CustomUserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class CustomUserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = CustomUser
        fields = ('email', 'password', 'is_active', 'is_staff')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.views.generic import edit
from django.contrib.auth import authenticate, login, logout, get_user
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from .models import Survey, Question, Answer, Publication
class LoginView(generic.View):
    template_name = 'main/login.html'
    def get(self,request,*args,**kwargs):
        return render(request,"main/login.html")
    def post(self,request,*args,**kwargs):
        username = request.POST['email']
        password = request.POST['password']    
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            context = {
                "not_user": True
            }
            return render(request,"main/login.html", context)
        return redirect(reverse_lazy('main:home'))
def logout_view(request):
    logout(request)
    return redirect("../")
def home_view(request):
    return render(request,"main/home.html",{})
class SurveyList(generic.ListView):
    model = Survey
    
class SurveyDetail(generic.DetailView):
    model = Survey
    fields = ['name','ask_count','surveyors','fee']    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['questions'] = Question.objects.filter(survey=self.object)
        return context
class SurveyCreate(edit.CreateView):
    model = Survey
    fields = ['name','ask_count','fee','created_by']
    success_url = reverse_lazy('main:survey_list')
class SurveyDelete(edit.DeleteView):
    model= Survey
    success_url = reverse_lazy('main:survey_list')

class SurveyUpdate(edit.UpdateView):
    model = Survey
    fields = ['name','ask_count','fee']
    def get_success_url(self):
        return reverse('main:survey_detail',kwargs={'pk': self.object.id})
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        context['questions'] = Question.objects.filter(survey=self.object)
        return context

class QuestionList(generic.ListView):
    model = Question
    def get_queryset(self):
        return Question.objects.filter(survey=Survey.objects.get(self.kwargs['pk']))

class QuestionDetail(generic.DetailView):
    model = Question
    fields = ['name']
    def get_object(self):
        return Question.objects.get(pk=self.kwargs['pk_q'])
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['answer_list'] = Answer.objects.filter(question=self.object)
        return context

class QuestionCreate(edit.CreateView):
    model = Question
    fields = ['name']
    def get_success_url(self):
        return reverse('main:survey_detail',kwargs={'pk': self.kwargs['pk']})
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['survey_name'] = Survey.objects.get(pk=self.kwargs['pk']).name
        return context
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.survey = Survey.objects.get(pk=self.kwargs['pk'])
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class QuestionDelete(edit.DeleteView):
    model = Question
    def get_object(self):
        return Question.objects.get(pk=self.kwargs['pk_q'])
    def get_success_url(self):
        return reverse('main:survey_detail',kwargs={'pk': self.kwargs['pk']})

class AnswerCreate(edit.CreateView):
    model = Answer
    fields = ['text']
    def get_success_url(self):
        return reverse('main:question_detail',kwargs={'pk': self.kwargs['pk'],'pk_q': self.kwargs['pk_q']})
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question_name'] = Question.objects.get(pk=self.kwargs['pk_q']).name
        return context
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.question = Question.objects.get(pk=self.kwargs['pk_q'])
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
class AnswerUpdate(edit.UpdateView):
    model = Answer
    fields = ['text']
    def get_success_url(self):
        return reverse('main:question_detail',kwargs={'pk': self.kwargs['pk'],'pk_q': self.kwargs['pk_q']})
    def get_object(self):
        return Answer.objects.get(pk=self.kwargs['pk_answer'])

class AnswerDelete(edit.DeleteView):
    model = Answer
    def get_object(self):
        return Answer.objects.get(pk=self.kwargs['pk_answer'])
    def get_success_url(self):
        return reverse('main:question_detail',kwargs={'pk': self.kwargs['pk'],'pk_q': self.kwargs['pk_q']})

class PublicationList(generic.ListView):
    template_name = 'main/publication_list.html'
    model = Publication
    def get_queryset(self):
        return self.request.user.publications.all
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['is_staff'] = self.request.user.is_staff
        return context

class PublicationDetail(generic.DetailView):
    model = Publication
    fields = ['header', 'source', 'date_published','date_created','text']
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['is_staff'] = self.request.user.is_staff
        return context

class PublicationUpdate(edit.UpdateView):
    model = Publication
    fields = ['header', 'source', 'date_published', 'text','releated_to']
    def get_success_url(self):
        return reverse_lazy('main:publication_detail',kwargs={'pk': self.kwargs['pk']})

class PublicationCreate(edit.CreateView):
    model = Publication
    fields = ['header', 'source', 'date_published', 'text','releated_to']
    success_url = reverse_lazy('main:publication_list')

class PublicationDelete(edit.DeleteView):
    model = Publication
    success_url = reverse_lazy('main:publication_list')

main/templates/main/answer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form method="post">{% csrf_token %}
        <p>"{{ object.text }}" Bu cevabı silmek istediğinizden emin misiniz?</p>
        <input class="btn btn-danger" type="submit" value="Evet">
        <a class="btn btn-secondary" href="{% url 'main:question_detail' object.question.survey.id object.question.id  %}">Hayır</a>
    </form>
</div>
{% endblock %}

main/templates/main/answer_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>{{question_name}}</h1>
<form class="form-control" method="post">{% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="Kaydet">
</form>
{% if object %}
    <a class="btn btn-danger" href="{% url 'main:answer_delete' object.question.survey.id object.question.id object.id %}">Cevabı Sil</a>
{% endif %}
{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}

{% block content %}
    <div id="about">
        <div class="container ">
        <div class="section-title text-center center wow bounce ">
            <h2>Hakkımızda</h2>
            <hr class="about">
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-6 text-center "> <img src="../static/img/biz.jpg" alt=""> </div>
            <div class="col-xs-12 col-md-6">
            <div class="about-text ">
            <p>
                Beşduyu medya takip şirketi olarak televizyon,sosyal medya,gazete,radyo gibi çeşitli medya organlarındaki  haberleri takip ve kayıt etmekteyiz.Müşterilerimizin istekleri doğrultusunda çeşitli medya organlarında yer alan kendileri ile ilgili bu haberleri onlara yine kendi istekleri doğrultusunda istedikleri sıklıkta rapor ediyoruz.
            </p>
            </div>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container loginform">
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <h3>Login</h3>
            </div>
          <div class="card-body">
            {% if not_user %}
              <div class="alert alert-danger" role="alert">
                Kullanıcı Bulunamadı
              </div>
            {% endif %}
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" class="form-control" placeholder="Email" name="email" required>
                    </div>

                    <div class="input-group form-group">

                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" class="form-control" placeholder="Şifre" name="password" required>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Giriş Yap" class="btn float-right login_btn btn-success">
                    </div>
                    <div class="form-group">
                        <a class="btn float-left login_btn btn-success" href="{% url 'main:login' %}" role="button" >Üye Ol</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

main/templates/main/publication_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form method="post">{% csrf_token %}
        <p>"{{ object.header }}" Bu yayını silmek istediğinizden emin misiniz?</p>
        <input class="btn btn-danger" type="submit" value="Evet">
        <a class="btn btn-secondary" href="{% url 'main:publication_detail' object.id  %}">Hayır</a>
    </form>
</div>
{% endblock %}

main/templates/main/publication_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>{{ object.header }}</h1>
    <p> {{ object.source }}</p>
    <p> {{ object.date_published }}</p>
    <p> {{ object.date_created }}</p>
    <p> {{ object.text }}</p>
    {% if is_staff %}
    <a class="btn btn-primary" href="{% url 'main:publication_update' object.id %}">Yayın Güncelle</a>
    <a class="btn btn-danger" href="{% url 'main:publication_delete' object.id %}">Yayın Sil</a>
    {% endif %}
</div>


{% endblock %}

main/templates/main/publication_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'Scripts/jquery.datetimepicker.css' %}"/>
<script src="{% static 'Scripts/jquery.js' %}"></script>
<script src="{% static 'Scripts/build/jquery.datetimepicker.full.min.js' %}"></script>
{% endblock %}

{% block content %}
<h1>{{survey_name}}</h1>
<form class="form-control" method="post">{% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="Kaydet">
</form>
{% if object %}
<a class="btn btn-danger" href="{% url 'main:publication_delete' object.id %}">Yayını Sil</a>
{% endif %}
<script>
    jQuery('#id_date_published').datetimepicker({
        format: 'Y-m-d H:i:s',
    });
</script>
{% endblock %}

main/templates/main/question_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form method="post">{% csrf_token %}
        <p>"{{ object.name }}" Bu soruyu silmek istediğinizden emin misiniz?</p>
        <input class="btn btn-danger" type="submit" value="Evet">
        <a class="btn btn-secondary" href="{% url 'main:survey_detail' object.survey.id  %}">Hayır</a>
    </form>
</div>
{% endblock %}

main/templates/main/question_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>{{ object.name }}</h1>
    
   
   
    <p>Cevaplar:</p>
    <ul>
        {% for a in answer_list %}
            <li><a href= "{% url 'main:answer_update' a.question.survey.id a.question.id a.id  %}">{{ a.text }}</li>
        {% endfor %}
    </ul>
    <a class="btn btn-primary" href="{% url 'main:answer_create' object.survey.id object.id %}">Cevap Ekle</a>
    <a class="btn btn-danger" href="{% url 'main:question_delete' object.survey.id object.id %}">Soruyu Sil</a>
</div>


{% endblock %}

main/templates/main/question_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>{{survey_name}}</h1>
<form class="form-control" method="post">{% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="Kaydet">
    </form>
{% endblock %}

main/templates/main/survey_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form method="post">{% csrf_token %}
        <p>"{{ object.name }}" İsimli anketi silmek istediğinizden emin misiniz?</p>
        <input class="btn btn-danger" type="submit" value="Evet">
        <a class="btn btn-secondary" href="{% url 'main:survey_detail' object.id  %}">Hayır</a>
    </form>
</div>
{% endblock %}

main/templates/main/survey_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>{{ object.name }}</h1>
    <p>Sorulacak Kişi Sayısı: {{ object.ask_count }}</p>
    <p>Ücret: {{ object.fee }}</p>
   
    <p>Sorulacak Sorular:</p>
    <ul>
        {% for q in questions %}
            <li>{{ q.name }}</li>
        {% endfor %}
    </ul>
    <a class="btn btn-primary" href="{% url 'main:survey_update' object.id  %}">Anketi Güncelle</a>
    <a class="btn btn-danger" href="{% url 'main:survey_delete' object.id  %}">Anketi Sil</a>
</div>


{% endblock %}

main/templates/main/survey_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form class="form-control" method="post">{% csrf_token %}
    {{ form|crispy }}
    <ul class="list-group">
        {% for q in questions %}
        <li class="list-group-item"><a href= "{% url 'main:question_detail' object.id q.id  %}"> {{ q.name }} </a></li>
        {% endfor %}
    </ul>
    {% if object %}
    <a class="btn btn-primary" href="{% url 'main:question_create' object.id %}">Soru Ekle</a></br></br>
    {% endif %}
    <input class="btn btn-success"  type="submit" value="Kaydet">
</form>
{% endblock %}

main/templates/main/survey_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Anketler</h2>
    <ul class="list-group">
        {% for object in object_list %}
        <li class="list-group-item"><a href= "{% url 'main:survey_detail' object.id  %}"> {{ object.name }} </a> </li>
        {% endfor %}
    </ul>
    <a class="btn btn-success" href="{% url 'main:survey_create' %}">Yeni Anket Oluştur</a>
</div>
{% endblock %}